### ISSUE TITLE
author_view not displayed on Studio

### ISSUE THREAD

**Issue by maykristine** [MEdXcognition/reflection#4] opened 2017-07-22 03:50 UTC
1. Add XBlock to a unit
Expected: When adding the XBlock on the Studio, the author_view should be displayed. 
Actual: Currently it looks like this (blank):
<img width="905" alt="screen shot 2017-07-22 at 12 44 45" src="https://user-images.githubusercontent.com/9590206/28488007-96732b10-6edb-11e7-86ef-c9c6606d8c56.png">

2. Click Edit
Expected: studio_view should be displayed
Actual: author_view is displayed

Occurs on May's devstack and on GATech's OpenEdX instance.

**Comment by ewall** [comment] 2017-07-22 19:03
It seems to me like edX Studio is ignoring the author_view altogether. Outside of edit mode, it always shows the student_view -- the initial blank view (item 1) is because the default student_view doesn't show anything until a block type has been chosen in studio_view. For that part, maybe we ought to have it default to showing the Preparation Phase block so it doesn't appear so empty?

And when we go into edit mode, it looks like the initial JavaScript that sets the field values isn't working, so it always defaults to no selections.

**Comment by maykristine** [comment] 2017-07-23 08:07
It is OK with me to just have the prep phase as default.
I changed it on the Python file and indeed it won't appear as empty anymore.
However, if I add a second XBlock on the same vertical, the a new uuid is not regenerated hence we are still having the same problem as we had before...
I am to try a very tedious idea right now:
- Edit / Author views have block_type = "" by default.
- When block_type is "", we display an html that only allows the user to select a block_type and does not reference any uuid.
- When a block_type is regenerated, we then attempt to display a studio_view / author_view

Maybe at this point we could have forced the Javascript to run? I still don't know why the author_view and studio_view are not displayable.

**Comment by ewall** [comment] 2017-07-23 15:21
studio_view is definitely trying to display in the edX Studio when you click the "Edit" button -- however, the JavaScript XBlock initialization (xblock.js) is failing when JQuery parses scripts in our XBlock. I think I'm on the trail to the cause of this now...

It still looks to me like edX Studio is completely ignoring the "author_view". At this point, I'd vote we just remove the author_view altogether to simplify.

**Comment by ewall** [comment] 2017-07-23 23:05
Unique UUID problem fixed (again) in https://github.com/MEdXcognition/reflection/commit/24972c832ebb2f4836e3f28aaf12786ee1f18b49

Remove author_view entirely in https://github.com/MEdXcognition/reflection/commit/6913b5bf55effb1c5669e0ee85bce8fb34dcee51

There are still JavaScript issues, but these fixes get us partway there...

**Comment by ewall** [comment] 2017-07-28 02:45
Remaining JavaScript errors are fixed in dd44b43f109ec7384d0600601d39a5cf0f73da1c, which is a whole new world from when we first filed this issue.

**Closed as completed by ewall** 2017-07-28 02:45 UTC

**Comment by maykristine** [comment] 2017-07-28 02:46
Hah! おめでとう！

**Comment by ewall** [comment] 2017-07-28 03:06
Arigato ;)
